development:
  source_name: 
  source_host: imap.gmail.com
  source_port: 993
  source_ssl: true
  source_user: 
  source_pass: 

test:
  source_name: posts@beilabs.com
  source_host: imap.gmail.com
  source_port: 993
  source_ssl: true
  source_user: 
  source_pass: 

production:
  source_name: 
  source_host: imap.gmail.com
  source_port: 993
  sourcel_ssl: true
  source_user: 
  source_pass: 

