development:
  adapter: postgresql
  database: beilabs_development
  username: jonathan
  password: dead@zone
  encoding: unicode
  host: /var/run/postgresql/

test:
  adapter: postgresql
  database: beilabs_test
  username: jonathan
  password: dead@zone
  encoding: unicode
  host: /var/run/postgresql/

cucumber:
  <<: *test

production:
  adapter: postgresql
  database: beilabs_production
  username: jonathan
  password: dead@zone
  encoding: unicode
  host: /var/run/postgresql/
